Feature/migration to net5.0
icgam/Easify.Ef pull request #13
Opened 2021-05-17 12:04 UTC by moattarwork

The PR includes the migration to .NET 5.0. As part of this change, the dependent assemblies move to .NET Standard 2.1

New Features

- .NET 5.0 support

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

The change has been tested with supporting unit and integration testing. 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-17 14:50 UTC, LewisPercival approved these changes

2021-05-17 15:14 UTC, davidcassell requested changes

2021-05-17 15:14 UTC, davidcassell commented on src/Easify.Ef.Testing.UnitTests/Easify.Ef.Testing.UnitTests.csproj
>          <LangVersion>8</LangVersion>
LangVersion is 9

2021-05-17 15:14 UTC, davidcassell commented on src/Easify.Ef.UnitTests/Easify.Ef.UnitTests.csproj
>    </PropertyGroup>
LangVersion

2021-05-18 11:50 UTC, davidcassell approved these changes

2021-05-18 14:44 UTC, richardcurtis-icg approved these changes

2021-05-20 08:33 UTC, merged